# Travis configuration file using the build matrix feature
# Read more under http://docs.travis-ci.com/user/build-configuration/
sudo: required
dist: trusty

services:
  docker

language: cpp

env:
  matrix:
    - CC_VER="5" PLATFORM='xenial'

before_install:
  - docker build --file travis/Dockerfile.${PLATFORM} -t builder-${PLATFORM} .
  - docker run -d --name builder -v $(pwd):/travis builder-${PLATFORM} tail -f /dev/null
  - docker ps

script:
  - docker exec -t -e CC_VER=${CC_VER} builder /root/build.sh

notifications:
    email: false
