# Travis configuration file using the build matrix feature
# Read more under http://docs.travis-ci.com/user/build-configuration/
sudo: required
dist: trusty

services:
  docker

language: cpp

env:
  matrix:
    - CC_VER="5" PLATFORM='xenial'

before_install:
  - ./travis/before_install.sh

script:
  - ./travis/build.sh

notifications:
    email: false
